# Github Action for PR builds, including Master branch and other "official" branches
name: PR Build

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # All operating systems
        node-version: [12.x, 13.x] # Current and LTS. No history versions

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Building
      run: |
        npm run boot
        npm run build
      env:
        CI: true
    - name: Unit test
      run: |
        npm run test
      env:
        CI: true
