name: Prime build

on:
  push:
    branches:
      - master
      - official/**

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        on: [ubuntu-latest, windows-latest, macos-latest] # All operating systems
        node-version: [12.x, 13.x] # Current and LTS. No history versions

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Building
      run: |
        npm run boot
        npm run build
      env:
        CI: true
    - name: Check change-file
      run: |
        npm run beachball:check
      env:
        CI: true
    - name: Unit test
      run: |
        npm run test
      env:
        CI: true
