name: Publish

# We use actions/checkout@V1 only in publishing.
# Otherwise, beachball cannot properly push the commit that clears change files.

on:
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch:
    types: manual-publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.repository == 'ot-builder/monorepo'

    steps:
    - name: Fetch main repository
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        token: ${{secrets.SECRET_GITHUB_TOKEN}}
    - name: Fetch docs repository
      uses: actions/checkout@v2
      with:
        repository: ot-builder/ot-builder.github.io.git
        ref: master
        path: .doc-deploy
        token: ${{secrets.SECRET_GITHUB_TOKEN}}
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: NPM Setup
      run: |
        npm run init:prod
      env:
        CI: true
    - name: Production Build
      run: |
        npm run build:prod
      env:
        CI: true
    - name: Publish
      run: |
        npm run publish
      env:
        SECRET_NPM_TOKEN: ${{secrets.SECRET_NPM_TOKEN}}
